"""initial migration

Revision ID: c0e0848d5cd1
Revises:
Create Date: 2026-08-18 10:30:38.074954

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c0e0848d5cd1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenders",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "ACTIVE", "WON", "LOST", name="tenderstatus"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tenders_created_by"), "tenders", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_tenders_status"), "tenders", ["status"], unique=False)
    op.create_table(
        "tender_history",
        sa.Column("tender_id", sa.Integer(), nullable=False),
        sa.Column("changed_by", sa.Integer(), nullable=False),
        sa.Column(
            "old_status",
            sa.Enum("DRAFT", "ACTIVE", "WON", "LOST", name="tenderstatus"),
            nullable=False,
        ),
        sa.Column(
            "new_status",
            sa.Enum("DRAFT", "ACTIVE", "WON", "LOST", name="tenderstatus"),
            nullable=False,
        ),
        sa.Column("reason", sa.TEXT(), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tender_id"], ["tenders.id"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tender_history_changed_by"),
        "tender_history",
        ["changed_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tender_history_new_status"),
        "tender_history",
        ["new_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tender_history_old_status"),
        "tender_history",
        ["old_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tender_history_tender_id"),
        "tender_history",
        ["tender_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tender_history_tender_id"), table_name="tender_history")
    op.drop_index(op.f("ix_tender_history_old_status"), table_name="tender_history")
    op.drop_index(op.f("ix_tender_history_new_status"), table_name="tender_history")
    op.drop_index(op.f("ix_tender_history_changed_by"), table_name="tender_history")
    op.drop_table("tender_history")
    op.drop_index(op.f("ix_tenders_status"), table_name="tenders")
    op.drop_index(op.f("ix_tenders_created_by"), table_name="tenders")
    op.drop_table("tenders")
    # ### end Alembic commands ###
